### ISSUE TITLE
hideNotification after component unmount

### ISSUE THREAD

**Issue by iceberk** [k4wo/react-notify#3]
Hello. Thanks for great component.
Is there any means to supress/disable hideNotification call after component was unmounted?

For example, if I called notificator with delay:
`notificator.error("Some error happend", "", 4000);`
and after that navigate to another component, I'm getting an error in console:
`warning.js:36 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Notify component.`

**Comment by k4wo** [comment]
It'a a bug. In the next version I will check if component is mounted. Thanks!

**Comment by k4wo** [comment]
@iceberk The new version has been released and bug should be fixed :-)
